title: Jak to format?
description: Tutorial dla osób czyszczących PC z windowsem
theme: just-the-docs

color_scheme: dark

url: https://wiki.fireword.xyz
repository: ThePhaseless/HowToFormat

heading_anchors: true

aux_links:
  "Revision OS":
    - "https://www.revi.cc/revios/download"
  "AMD Drivers":
    - "https://www.amd.com/en/support"
  "Nvidia Drivers":
    - "https://www.nvidia.com/Download/index.aspx?lang=en-us"
  "Intel Drivers":
    - "https://downloadcenter.intel.com/"

callouts:
  warning:
    title: Uwaga
    color: red
  note:
    title: Wyjaśnienie
    color: blue
  info:
    title: Informacja
    color: yellow
